[package]
name = "hello_world"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "MIT"
authors = ["Bridget", "David"]

[dependencies]
# For remote import, use `{ git = "...", subdir = "...", rev = "..." }`.
# MyRemotePackage = { git = "https://some.remote/host.git", subdir = "remote/path", rev = "main" }
# For local deps: Local = { local = "../path/to" }
# To force a version: Override = { local = "../conflicting/version", override = true }

[addresses]
hello_world = "0x0"
# alice = "0xA11CE"

[dev-dependencies]
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# alice = "0xB0B"

